### ISSUE TITLE
CoxPHFitter() - ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by arvchi** [CamDavidsonPilon/lifelines#516] opened 2018-10-10 09:09 UTC
I try to use the CoxPHFitter() function. It works on many of my iterations, but halts on a specific row, with the error code:

```
ValueError: array must not contain infs or NaNs
```

This is the code that I use to call the function. 

```
cph = CoxPHFitter()
cph.fit(dftsubset, duration_col='LivingDays', event_col='Status', show_progress=True)
```

The data file is to huge to be attached here, but from what I can see there are no Na's or inf's. The code below yields an empty dataframe.

```
dftsubset[dftsubset.isin([np.nan, np.inf, -np.inf]).any(1)]
```

Any help appreciated!

**Comment by CamDavidsonPilon** [comment] 2018-10-10 09:50
Can you post the output of the fitting with show_progress=True? I’d like to see the convergence details?

Are there any warnings displayed?

**Comment by norbertstrzelecki** [comment] 2018-10-10 10:03
@arvchi meanwhile, waiting for the answer from @CamDavidsonPilon, try with smaller 'step_size' value like 0.1-0.5 as stated in docs.

**Comment by arvchi** [comment] 2018-10-10 11:07
@CamDavidsonPilon Here is the full output:

```
cph.fit(dftsubset, duration_col='LivingDays', event_col='Status', show_progress=True)
Iteration 1: norm_delta = 0.50183, step_size = 0.95000, ll = -664.70188, seconds_since_start = 0.0
Iteration 2: norm_delta = 0.61543, step_size = 0.95000, ll = -705.82463, seconds_since_start = 0.0
Iteration 3: norm_delta = 1.07325, step_size = 0.95000, ll = -667.56621, seconds_since_start = 0.0
Iteration 4: norm_delta = 1.34934, step_size = 0.93100, ll = -860.48955, seconds_since_start = 0.0
Iteration 5: norm_delta = 2.57636, step_size = 0.91238, ll = -675.66214, seconds_since_start = 0.1
Iteration 6: norm_delta = 12.86979, step_size = 0.89413, ll = -1521.83406, seconds_since_start = 0.1
Iteration 7: norm_delta = 173.42957, step_size = 0.65719, ll = -1086.23141, seconds_since_start = 0.1
/Users/arvin/anaconda3/lib/python3.6/site-packages/lifelines/fitters/coxph_fitter.py:321: RuntimeWarning: overflow encountered in exp
  phi_i = w * exp(dot(xi, beta))
/Users/arvin/anaconda3/lib/python3.6/site-packages/lifelines/fitters/coxph_fitter.py:353: RuntimeWarning: invalid value encountered in multiply
  denom = (risk_phi - c * tie_phi)
/Users/arvin/anaconda3/lib/python3.6/site-packages/lifelines/fitters/coxph_fitter.py:354: RuntimeWarning: invalid value encountered in multiply
  z = (risk_phi_x - c * tie_phi_x)
/Users/arvin/anaconda3/lib/python3.6/site-packages/lifelines/fitters/coxph_fitter.py:359: RuntimeWarning: invalid value encountered in multiply
  a1 = (risk_phi_x_x - c * tie_phi_x_x) / denom
/Users/arvin/anaconda3/lib/python3.6/site-packages/lifelines/fitters/coxph_fitter.py:357: RuntimeWarning: invalid value encountered in true_divide
  partial_gradient += z / denom
/Users/arvin/anaconda3/lib/python3.6/site-packages/lifelines/fitters/coxph_fitter.py:359: RuntimeWarning: invalid value encountered in true_divide
  a1 = (risk_phi_x_x - c * tie_phi_x_x) / denom
/Users/arvin/anaconda3/lib/python3.6/site-packages/lifelines/fitters/coxph_fitter.py:362: RuntimeWarning: invalid value encountered in true_divide
  a2 = dot(z.T / denom, z / denom)
Traceback (most recent call last):

  File "<ipython-input-96-5ae67cf849c6>", line 1, in <module>
    cph.fit(dftsubset, duration_col='LivingDays', event_col='Status', show_progress=True)

  File "/Users/arvin/anaconda3/lib/python3.6/site-packages/lifelines/fitters/coxph_fitter.py", line 149, in fit
    step_size=step_size)

  File "/Users/arvin/anaconda3/lib/python3.6/site-packages/lifelines/fitters/coxph_fitter.py", line 237, in _newton_rhaphson
    delta = spsolve(-h, step_size * g.T, sym_pos=True)

  File "/Users/arvin/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py", line 140, in solve
    a1 = atleast_2d(_asarray_validated(a, check_finite=check_finite))

  File "/Users/arvin/anaconda3/lib/python3.6/site-packages/scipy/_lib/_util.py", line 238, in _asarray_validated
    a = toarray(a)

  File "/Users/arvin/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 1233, in asarray_chkfinite
    "array must not contain infs or NaNs")

ValueError: array must not contain infs or NaNs
```

**Comment by CamDavidsonPilon** [comment] 2018-10-10 12:05
> Iteration 7: norm_delta = 173.42957, step_size = 0.65719, ll = -1086.23141, seconds_since_start = 0.1

yea, looks like the convergence fails (and some `exp(value)` creates infs). So try a smaller step size as @norbertstrzelecki suggests. Also, what version of lifelines are you using? 
```
import lifelines
lifelines.__version__
```

**Comment by CamDavidsonPilon** [comment] 2018-10-10 12:07
For v0.15 release, I'll add better error handling for this.

**Comment by CamDavidsonPilon** [comment] 2018-10-10 13:48
There are two warnings you need to look at: 
```
ConvergenceWarning: "Column(s) ['ENSG00000100146'] have very low variance. This may harm convergence. Try dropping this redundant column before fitting if convergence fails."

ConvergenceWarning: "Column(s) ['ENSG00000100146'] have very low variance when conditioned on death event or not. This may harm convergence. This could be a form of 'complete separation'. See https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faqwhat-is-complete-or-quasi-complete-separation-in-logisticprobit-regression-and-how-do-we-deal-with-them/ "
```

**Comment by CamDavidsonPilon** [comment] 2018-10-11 12:33
I'm closing this as the problem is a variable in the input, but adding more error handling to lifelines in response

**Closed by CamDavidsonPilon** 2018-10-11 12:33 UTC
Labels: better error handling, convergence issue, hopefully next release 🤞
