### ISSUE TITLE
Time (duration) and event columns in separate dataframes

### ISSUE THREAD

**Issue by helangen** [CamDavidsonPilon/lifelines#1137] opened 2020-09-17 17:55 UTC
Hi,

I have an issue with the 'durations' and 'events' columns going into the kmf.fit() function. I previously had a dataframe with both the durations (as integers [days]) and the events (as boolean [0,1]). Using the kmf.fit() function the KM-curve looked accurate with the censored patients at the right times. e.g. the first patient got censored at time 1083 days. The index of the dataframe was patient ID codes (i.e. 1001, 1002, 1003, ...)

I did some cleaning up of the code and tried to plot this KM-curve in another Jupyter Notebook. The only difference now was that this information about 'durations' and 'events' was in two separate dataframes, but both with the same index (patient ID). Now plotting this KM-curve gives me a different curve. e.g. 4 censored patients before time 500 days, but this is not correct looking at the data. I tried to change the 'durations' data type to float, and this gives me another curve with, e.g. 6 censored patients before time 500 days. If I create a dataframe of these two dataframes above, only then can I get the same (and correct KM curve).

Is this a bug or intended usage that the 'durations' and 'events' needs to be from the same dataframe?

I use Python 3.8, lifelines 0.25.4 and matplotlib 3.2.2.

Kind Regards
Henning

**Comment by CamDavidsonPilon** [comment] 2020-09-17 18:25
Hi @helangen 

This is very strange. A few thoughts:

1) Can you confirm that the data in the `events` look correct? 

2) To remove the possibilities of Pandas / indexes playing a role, can you try using `.values` to cast to numpy arrays?

3) Is the index in the same _order_ between the trials? When given a Series or DataFrame, [lifelines will ignore the index](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/kaplan_meier_fitter.py#L294-L299) anyways, so of the data is out of order originally, it won't be corrected. 


> Is this a bug or intended usage that the 'durations' and 'events' needs to be from the same dataframe?

Definitely not intended.

**Comment by helangen** [comment] 2020-09-18 06:10
Hi again,

The data that is used is the same data, just in one instance they are collected from two separate dataframes, whilst in the other instance they are split and then concatenated into one dataframe. Only the last instance gives the correct KM curve.

1. Yes, the data in the 'events' column is correct. They are all 0 and 1s.

2. Tried to append '.values' with no change. Still the wrong KM curve.

3. This is not two trials, but one. Originally the values where not sorted on index so I tried to sort it. It did not make a difference.

Snippets from the code:

This does not give me the correct KM curve.
`# Generate 'durations' and 'events' for analysis`
`durations_all = dataframe_1['OS (days)'] ## where 'OS days' are float64`
`event_observed_all = pd.get_dummies(dataframe_2['Status'])['Dead'] ## Where alive=1 and dead=0`

This does
`test = pd.DataFrame(data=pd.get_dummies(dataframe_2['Status'])['Dead'] ## Where alive=1 and dead=0, index=event_observed_all.index)`
`test['durations'] = dataframe_1['OS (days)']`
`test.sort_index()`
`durations_all = test['durations']`
`event_observed_all = test['Dead']`

Henning

**Comment by CamDavidsonPilon** [comment] 2020-09-18 13:25
> ## Where alive=1 and dead=0

This should be the opposite: dead should have a flag of 1.

I think the problem is the order of your data. In the first code snippet, the two datasets (`durations_all`, and `event_observed_all`) are never "merged" and because lifelines treat observations as pairwise, that is, the first duration corresponds to the first event observed, and so on, we _must_ be sure that this corresponds to the correct ordering. In the second snippet, the line `test['durations'] = dataframe_1['OS (days)']` will align index between `test` and `dataframe_1` so that any out of order data is corrected. Does that make sense? 

I guess what I am saying is: I think your data is out of order prior to lifelines seeing it. For a test, compare the outputs of:
```
kmf.event_observed 
kmf.durations
```

between the two cases. I suspect they are not identical.

**Comment by helangen** [comment] 2020-09-18 16:11
Sorry, I meant alive=0, dead=1. My mistake.

**_"I think the problem is the order of your data. In the first code snippet, the two datasets (durations_all, and event_observed_all) are never "merged" and because lifelines treat observations as pairwise, that is, the first duration corresponds to the first event observed, and so on, we must be sure that this corresponds to the correct ordering"_**

Yes, that is what I thought as well. So I sorted the indices in both 'durations' and 'columns' to make sure of this. So I added
`durations_all.sort_index()`
`event_observed_all.sort_index()`
to the end of the first code snippet (sorry they didn't get copied in my last reply). This in my head should be the same sort as in the dataframe in the second code snippet.

**_In the second snippet, the line test['durations'] = dataframe_1['OS (days)'] will align index between test and dataframe_1 so that any out of order data is corrected. Does that make sense?_**

Yes, it does. I thought this was the problem initially as well.

**_Let me modify that test, actually, since I don't think it's sufficient. Try comparing sorted(zip(kmf.durations, kmf.event_observed)) between the two cases._**

With two separate dataframes:
`[(39.0, 1),
 (56.0, 1),
 (57.0, 1),
 (57.0, 1),
 (85.0, 1),
 (95.0, 1),
 (99.0, 1),
 (103.0, 1),
 (110.0, 1),
 (119.0, 1),
 (128.0, 0),
 (128.0, 1),
 (143.0, 1),
 (147.0, 1),
 (167.0, 1),
 (173.0, 1),
 (173.0, 1),
 (174.0, 1),
 (174.0, 1),
 (226.0, 1),
 (227.0, 1),
 (233.0, 0),
 (247.0, 1),
 (260.0, 1),
 (266.0, 1),
 (309.0, 1),
 (318.0, 0),
 (319.0, 1),
 (325.0, 1),
 (364.0, 1),
 (369.0, 1),
 (375.0, 1),
 (412.0, 1),
 (421.0, 1),
 (453.0, 1),
 (455.0, 1),
 (459.0, 1),
 (471.0, 0),
 (473.0, 1),
 (514.0, 1),
 (542.0, 1),
 (558.0, 1),
 (583.0, 1),
 (588.0, 0),
 (588.0, 1),
 (603.0, 1),
 (646.0, 1),
 (694.0, 1),
 (733.0, 1),
 (762.0, 1),
 (778.0, 1),
 (792.0, 1),
 (807.0, 1),
 (890.0, 0),
 (1031.0, 1),
 (1035.0, 1),
 (1084.0, 1),
 (1147.0, 1),
 (1210.0, 1),
 (1404.0, 1),
 (1410.0, 1),
 (1480.0, 1),
 (1495.0, 0),
 (1600.0, 1),
 (1622.0, 1),
 (1878.0, 1),
 (1887.0, 1),
 (2047.0, 1),
 (2239.0, 0),
 (2421.0, 1),
 (2631.0, 0)]`

With data in the same dataframe:
`[(39.0, 1),
 (56.0, 1),
 (57.0, 1),
 (57.0, 1),
 (85.0, 1),
 (95.0, 1),
 (99.0, 1),
 (103.0, 1),
 (110.0, 1),
 (119.0, 1),
 (128.0, 1),
 (128.0, 1),
 (143.0, 1),
 (147.0, 1),
 (167.0, 1),
 (173.0, 1),
 (173.0, 1),
 (174.0, 1),
 (174.0, 1),
 (226.0, 1),
 (227.0, 1),
 (233.0, 1),
 (247.0, 1),
 (260.0, 1),
 (266.0, 1),
 (309.0, 1),
 (318.0, 1),
 (319.0, 1),
 (325.0, 1),
 (364.0, 1),
 (369.0, 1),
 (375.0, 1),
 (412.0, 1),
 (421.0, 1),
 (453.0, 1),
 (455.0, 1),
 (459.0, 1),
 (471.0, 1),
 (473.0, 1),
 (514.0, 1),
 (542.0, 1),
 (558.0, 1),
 (583.0, 1),
 (588.0, 1),
 (588.0, 1),
 (603.0, 1),
 (646.0, 1),
 (694.0, 1),
 (733.0, 1),
 (762.0, 1),
 (778.0, 1),
 (792.0, 1),
 (807.0, 1),
 (890.0, 1),
 (1031.0, 1),
 (1035.0, 1),
 (1084.0, 0),
 (1147.0, 0),
 (1210.0, 1),
 (1404.0, 1),
 (1410.0, 1),
 (1480.0, 0),
 (1495.0, 0),
 (1600.0, 0),
 (1622.0, 1),
 (1878.0, 0),
 (1887.0, 1),
 (2047.0, 1),
 (2239.0, 0),
 (2421.0, 0),
 (2631.0, 0)]`

**Comment by CamDavidsonPilon** [comment] 2020-09-18 20:20
So the data is different, in at least one place: `2421.0`, for example. This implies the input data to lifelines isn't the same. I would use this hint to track down where the bug is in the preprocessing.

**Comment by helangen** [comment] 2020-09-19 10:01
Yeah, I can see that for several instances it gives different durations. I will look at the columns again. I could swear they were similar. Thanks.

**Comment by CamDavidsonPilon** [comment] 2020-09-19 13:12
Good to hear it is resolved! 🙏

**Closed by CamDavidsonPilon** 2020-09-19 13:12 UTC
