### ISSUE TITLE
Option to return survival function for left-censored data? 

### ISSUE THREAD

**Issue by elnjensen** [CamDavidsonPilon/lifelines#291] opened 2017-05-17 14:17 UTC
The current code calculates the survival function for a Kaplan-Meier fit of right-censored data, but instead returns the cumulative density function for left-censored data.  In my field of astronomy, where the left-censoring often involves upper limits not on timespans but on other quantities (for example the brightness of sources, which can only be detected if they are above some fixed brightness value), we are often still interested in an estimate of what I would call the cumulative distribution of brightness, which I think is equivalent to the survival function ("what fraction are still alive at this time?" becomes "what fraction are brighter than this value?").  

The terminology between fields is a little different, but is the cumulative density function just 1 - (survival function)? 

Would it be possible to give the user the option to return the survival function rather than the cumulative density function?  I can see [here](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/kaplan_meier_fitter.py#L47) where one could make the switch in the Kaplan-Meier code, but I'm not sure if there's some subtlety in calculating the estimators with different kinds of censorship that I'm unaware of.  

Thanks for the code, and for considering this.

**Comment by CamDavidsonPilon** [comment] 2017-05-21 18:20
`is the cumulative density function just 1 - (survival function)?`

Yes, it should be (assuming I'm not forgetting something obvious)

Now, I wonder why I return the CDF vs the SF in left-trunc, let me dig in more.

**Comment by CamDavidsonPilon** [comment] 2017-05-21 18:28
My notes suggest looking at http://www.public.iastate.edu/~pdixon/stat505/Chapter%2011.pdf, specfically section 11.3. Basically, when you have left-censored data, then we estimate the CDF (because it is "easier" to estimate). Switching to the survival function is indeed just the compliment of the CDF. 

To add an API to do this? Maybe, I'd like to see more users with left-censored data _prefer_ the SF. My prior belief is that one care's more about the CDF when one has left-censored data.

**Comment by fbianchini** [comment] 2017-08-28 05:57
Hi all, I'm also dealing with left-censored data in the context of astronomical analysis. After feeding the KM fitter class with the inputs, i.e. flux of sources and a boolean array specifying whether it's a detection or not, I manage to compute the CDF (or the SF as 1 - CDF) but then the median value is always inf, no matter what's the fraction of censored data. Am I overlooking something trivial here? Thanks for the help and for releasing such a nice code!

**Comment by CamDavidsonPilon** [comment] 2017-08-28 13:24
@fbianchini hey there - can you provide the dataset and code you are using? That would help me understand what you are seeing.

**Comment by fbianchini** [comment] 2017-08-28 14:13
Hey @CamDavidsonPilon, thanks for your quick reply! 
`import numpy as np
from lifelines import KaplanMeierFitter

kmf_W4 = KaplanMeierFitter()
`

**Comment by fbianchini** [comment] 2017-08-28 14:15
Hey @CamDavidsonPilon, thanks for your quick reply! 
```
import numpy as np
from lifelines import KaplanMeierFitter

kmf = KaplanMeierFitter()
```

**Comment by fbianchini** [comment] 2017-08-28 14:23
Hey @CamDavidsonPilon, thanks for your quick reply! 
Below there's a snippet of code that reproduces such behaviour, while the data can be accessed [here](https://www.dropbox.com/s/utusu2ik6k1oirk/fluxes_KM_test.dat?dl=0), first column contains the fluxes and the second one tells whether the object is detected (=1) or not (=0): 
```
import numpy as np
from lifelines import KaplanMeierFitter

fluxes, detected = np.loadtxt('fluxes_KM_test.dat', unpack=True)

kmf = KaplanMeierFitter()
kmf.fit(fluxes, event_observed=detected, left_censorship=True)
print kmf.median_
```

**Comment by CamDavidsonPilon** [comment] 2017-08-28 23:24
Right, looks like `median_` is only defined correctly if `left_censorship=False`. For now you can use:
```python
median_ = (kmf.cumulative_density_ <= 0.5).idxmin(0)
```

I'll PR a fix for this.

**Comment by fbianchini** [comment] 2017-08-28 23:47
Oh I see, thanks for the clarification. One more thing: if I want to calculate the median of the associated survival function, should I use something like
'''
median_ = ((1.-kmf.cumulative_density_) >= 0.5).idxmin(0)
'''
Thanks!

**Comment by CamDavidsonPilon** [comment] 2017-08-28 23:51
well, the median _should_ be the same, whether you are looking at the survival curve or the cdf (this is only true for the median)

**Comment by fbianchini** [comment] 2017-08-28 23:52
...and indeed it is! Sorry for the dumb question :)

**Comment by fbianchini** [comment] 2017-09-08 06:44
Hi Cameron, sorry to bug you again but I thought you could help me understanding the attached plot. What you see there is the CDF obtained from the data that I shared above. Do you have any insights on the reason it doesn't go to zero for S_nu -> 0? Thanks!

[KM_CDF.pdf](https://github.com/CamDavidsonPilon/lifelines/files/1286974/KM_CDF.pdf)

**Closed** 2019-03-23 13:33 UTC

**Comment by CamDavidsonPilon** [comment] 2019-03-23 13:37
FYI `survival_function_` and `cumulative_density_` is now always available
