### ISSUE TITLE
Bad concordance I don't know why ?

### ISSUE THREAD

**Issue by 7belrhalmia** [CamDavidsonPilon/lifelines#460] opened 2018-05-16 09:26 UTC
Hello, 

I have an issue  :  

here is my data  : 

![image](https://user-images.githubusercontent.com/13202562/40106945-5bac9a8c-58f7-11e8-9a74-5ca7e83e232d.png)

the time is the first column and the event is the second column.

I do this code to fit the model : 

![image](https://user-images.githubusercontent.com/13202562/40107039-8cb9223a-58f7-11e8-8cf7-c1784d0fac63.png)

However i am obtaining a bad concordance 0.067  I don't know why!

![image](https://user-images.githubusercontent.com/13202562/40108688-f9c28188-58fb-11e8-991e-a77913861c0e.png)

Concordance = 0.061

**Comment by CamDavidsonPilon** [comment] 2018-05-16 11:36
Wow that is very strange. I would expect a lower bound of 0.5, not something so low. 

Can you run the .fit again but turn on the show_progress parameter? And then please display the results?

**Comment by 7belrhalmia** [comment] 2018-05-16 12:36
Here is the results : 


![image](https://user-images.githubusercontent.com/13202562/40117169-6ff9ea3e-5916-11e8-8606-f7c16de3d3e6.png)

**Comment by CamDavidsonPilon** [comment] 2018-05-17 15:52
Are you able to share the dataset with me? I can't think of any reason why this is happening.

**Comment by CamDavidsonPilon** [comment] 2018-10-12 19:32
Pretty sure this is caused by a concordance index overflow error, fixed in to be released v0.15

**Closed** 2018-11-22 21:51 UTC
